AWSTemplateFormatVersion: 2010-09-09
Description: >
  Deploys a ECS cluster to the platform infrastructure.

Parameters:
  ClusterName:
    Description: ECS cluster name
    Type: String
  VpcId:
    Description: VPC id where cluster networking resources will live
    Type: String
  SubnetIds:
    Description: Available Subnets Ids where cluster networking resources will live
    Type: CommaDelimitedList

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
